### ISSUE TITLE
support for realtime live chat

### ISSUE THREAD

**Issue by skochinsky** [nlitsme/youtube_tool#2]
When trying to dump a live chat from a live stream in progress (or before the video starts), the following stack trace is produced:

```
Traceback (most recent call last):
  File "yttool.py", line 857, in <module>
    main()
  File "yttool.py", line 844, in main
    txt.recursechat()
  File "yttool.py", line 271, in recursechat
    cmtlist, newms = self.extractchat(js)
  File "yttool.py", line 289, in extractchat
    for act in actions:
TypeError: 'NoneType' object is not iterable

```
I dumped  the 'js' and the `response` dictionary looks as follows:

```
    'response': {
        'responseContext': {
            'errors': {
                'error': [{
                    'domain': 'gdata.CoreErrorDomain',
                    'code': 'INVALID_VALUE',
                    'location': 'continuation',
                    'externalErrorMessage': 'Unknown error.'
                }]
            },
            'serviceTrackingParams': [{
                'service': 'CSI',
                'params': [{
                    'key': 'GetLiveChatReplay_rid',
                    'value': '0x64d7c7c517b03040'
                }, {
                    'key': 'c',
                    'value': 'WEB'
                }, {
                    'key': 'cver',
                    'value': '2.20200603.01.00'
                }, {
                    'key': 'yt_li',
                    'value': '0'
                }]
            }, {
                'service': 'GFEEDBACK',
                'params': [{
                    'key': 'e',
                    'value': '23744176,23768780,23804281,23826896,23839597,23856950,23857949,23862346,23868322,23882503,23884386,23890959,23895671,23910804,23911055,23914825,23915654,23915992,23916148,23918597,23921357,23921554,23923266,23928508,23930220,23934145,23934970,23938050,23938801,23940093,23940248,23942338,23944779,23945378,23947185,23947333,23947421,23947582,23947699,23948418,23948841,23949503,23949704,23950597,23951139,9407157,9449243'
                }, {
                    'key': 'logged_in',
                    'value': '0'
                }]
            }, {
                'service': 'GUIDED_HELP',
                'params': [{
                    'key': 'logged_in',
                    'value': '0'
                }]
            }, {
                'service': 'ECATCHER',
                'params': [{
                    'key': 'client.name',
                    'value': 'WEB'
                }, {
                    'key': 'client.version',
                    'value': '2.20200827'
                }, {
                    'key': 'innertube.build.changelist',
                    'value': '333329088'
                }, {
                    'key': 'innertube.build.experiments.source_version',
                    'value': '333819257'
                }, {
                    'key': 'innertube.build.label',
                    'value': 'youtube.ytfe.innertube_20200922_1_RC1'
                }, {
                    'key': 'innertube.build.timestamp',
                    'value': '1600884732'
                }, {
                    'key': 'innertube.build.variants.checksum',
                    'value': '122acbbceb83a90e0f7b1e64d246da31'
                }, {
                    'key': 'innertube.run.job',
                    'value': 'ytfe-innertube-replica-only.ytfe'
                }]
            }],
            'webResponseContextExtensionData': {
                'ytConfigData': {
                    'csn': 'ax1vX6-UNZDW1wKu3pm4CQ',
                    'visitorData': 'CgtPeUNEcERtRmI3dyjrurz7BQ%3D%3D'
                },
                'hasDecorated': True
            }
        },
        'trackingParams': 'CAAQ0b4BIhMI4q--1dOG7AIVmLh7Ch3OOQnL'
    },

```

**P.S.** I could dump the log after the stream ended but it would be nice to have it write the log as it happens (e.g. to not miss the end of the stream or in case some messages are removed later).

**Comment by nlitsme** [comment]
note that i still have this on my todo list

**Comment by nlitsme** [comment]
realtime livechat should work too now.

Let me know when you find any problems.
