### ISSUE TITLE
noneType errors 

### ISSUE THREAD

**Issue by kcchrist** [nlitsme/youtube_tool#3]
When Executing yttool, python 3.8.5 throws this error: 

```
yttool -c https://www.youtube.com/watch?v=1LWEXRAnQd0

Traceback (most recent call last):

  File "/usr/local/bin/yttool", line 8, in <module>
    sys.exit(main())

  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 913, in main
    cmt = CommentReader(args, yt, cfg)

  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 344, in __init__
    self.contclick, self.xsrf = self.getcommentinfo(cfg)

  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 392, in getcommentinfo
    cont = self.getcontinuation(getitem(item, ("itemSectionRenderer",), "itemSectionRenderer")) 

  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 68, in getitem
    d = getitembymember(d, *k)

  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 54, in getitembymember
    for item in a:

TypeError: 'NoneType' object is not iterable
```

Any advice or ideas on how to clean up unassigned objects? It seems that a, d and other values are assigned None. 

Please let me know if I can share any more info for diagnostics.

**Comment by nlitsme** [comment]
The problem is that this video is 'not playable'

I added a check for 'playability'  Now yttool will print a more friendly error message.

**Comment by kcchrist** [comment]
Thank you. I feel like an idiot now. Thank you for helping to handle this "user is an idiot" exception.
