### ISSUE TITLE
when trying to download comments from a video te following error occured on my terminal

### ISSUE THREAD

**Issue by lams98** [nlitsme/youtube_tool#4]
Part 2 - using the theorem to show some cool stuff: https://youtu.be/o3QBgkQi_HA
And a bit extra on inversion: https://youtu.be/qmfFH1SyXP0
Traceback (most recent call last):
  File "/usr/local/bin/yttool", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 940, in main
    cmt.recursecomments()
  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 409, in recursecomments
    self.recursecomments(subcc, level+1)
  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 409, in recursecomments
    self.recursecomments(subcc, level+1)
  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 409, in recursecomments
    self.recursecomments(subcc, level+1)
  [Previous line repeated 972 more times]
  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 392, in recursecomments
    cmtjson = self.yt.getcomments(cc, self.xsrf)
  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 179, in getcomments
    return self.httpreq(url + "?" + urllib.parse.urlencode(query), postdata.encode('ascii') )
  File "/usr/local/lib/python3.8/dist-packages/yttool.py", line 155, in httpreq
    response = self.opener.open(req, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/lib/python3.8/http/client.py", line 225, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/usr/lib/python3.8/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/usr/lib/python3.8/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/usr/lib/python3.8/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/usr/lib/python3.8/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/usr/lib/python3.8/email/feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "/usr/lib/python3.8/email/message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "/usr/lib/python3.8/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "/usr/lib/python3.8/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/usr/lib/python3.8/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "/usr/lib/python3.8/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "/usr/lib/python3.8/email/utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by lams98** [comment]
i was trying to download the comments from the numberphile video that use as an example

**Comment by nlitsme** [comment]
thanks for letting me know.  It seems something has changed. I will look into it.

**Comment by nlitsme** [comment]
It seems youtube now requires the use of the `action_get_comment_replies` parameter to `comment_service_ajax`

**Comment by nlitsme** [comment]
I pushed an update, let me know if this works for you now.

**Comment by lams98** [comment]
worked thanks but I have to manually install it to start working

**Comment by nlitsme** [comment]
I now updated the pypi package too.
